/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        menuHospedes = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospedes = new javax.swing.JMenuItem();
        menuQuartos = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuartos = new javax.swing.JMenuItem();
        meunoFuncionarios = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuConProdutos = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menuCadServicos = new javax.swing.JMenuItem();
        menuConServicos = new javax.swing.JMenuItem();
        reservas = new javax.swing.JMenu();
        menuCadReservas = new javax.swing.JMenuItem();
        menuConReservas = new javax.swing.JMenuItem();
        menuFinalizarReserva = new javax.swing.JMenuItem();
        vendas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        financeiro = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        seguranca = new javax.swing.JMenu();
        ferramentas = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        sair7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistela de Gerenciamento de Reservas");

        cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cadastro-30.png"))); // NOI18N
        cadastro.setText("Cadastros   ");
        cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-ela-20.png"))); // NOI18N
        menuHospedes.setText("Hospedes");

        menuCadHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadHospede.setText("Cadastrar");
        menuHospedes.add(menuCadHospede);

        menuConHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConHospedes.setText("Consultar");
        menuHospedes.add(menuConHospedes);

        cadastro.add(menuHospedes);

        menuQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cama-20.png"))); // NOI18N
        menuQuartos.setText("Quartos");

        menuCadQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadQuartos.setText("Cadastrar");
        menuQuartos.add(menuCadQuartos);

        menuConQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConQuartos.setText("Consultar");
        menuQuartos.add(menuConQuartos);

        cadastro.add(menuQuartos);

        meunoFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-carregador-de-malas-20.png"))); // NOI18N
        meunoFuncionarios.setText("Funcionários");

        menuCadFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadFuncionarios.setText("Cadastrar");
        meunoFuncionarios.add(menuCadFuncionarios);

        menuConFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConFuncionarios.setText("Consultar");
        meunoFuncionarios.add(menuConFuncionarios);

        cadastro.add(meunoFuncionarios);

        menuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-20.png"))); // NOI18N
        menuFornecedores.setText("Fornecedores");

        menuCadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadFornecedores.setText("Cadastrar");
        menuCadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(menuCadFornecedores);

        menuConFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConFornecedores.setText("Consultar");
        menuFornecedores.add(menuConFornecedores);

        cadastro.add(menuFornecedores);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mover-por-carrinho-20.png"))); // NOI18N
        menuProdutos.setText("Produtos");

        menuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadProdutos.setText("Cadastar");
        menuProdutos.add(menuCadProdutos);

        menuConProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConProdutos.setText("Consultar");
        menuProdutos.add(menuConProdutos);

        cadastro.add(menuProdutos);

        menuServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-serviço-20.png"))); // NOI18N
        menuServicos.setText("Servicos");

        menuCadServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        menuCadServicos.setText("Cadastrar");
        menuServicos.add(menuCadServicos);

        menuConServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        menuConServicos.setText("Consultar");
        menuServicos.add(menuConServicos);

        cadastro.add(menuServicos);

        jMenuBar1.add(cadastro);

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-calendário-30.png"))); // NOI18N
        reservas.setText("Reservas   ");
        reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mais-calendário-20.png"))); // NOI18N
        menuCadReservas.setText("Cadastrar Reserva");
        menuCadReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadReservasActionPerformed(evt);
            }
        });
        reservas.add(menuCadReservas);

        menuConReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-calendário-de-folgas-20.png"))); // NOI18N
        menuConReservas.setText("Consultar Reserva");
        reservas.add(menuConReservas);

        menuFinalizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-menos-calendário-20.png"))); // NOI18N
        menuFinalizarReserva.setText("Finalizar Reserva");
        reservas.add(menuFinalizarReserva);

        jMenuBar1.add(reservas);

        vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-bens-de-consumo-rápido-30.png"))); // NOI18N
        vendas.setText("Vendas   ");
        vendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mover-por-carrinho-20.png"))); // NOI18N
        jMenuItem1.setText("Produtos");
        vendas.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-serviço-20.png"))); // NOI18N
        jMenuItem2.setText("Servicos");
        vendas.add(jMenuItem2);

        jMenuBar1.add(vendas);

        financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-faturamento-30.png"))); // NOI18N
        financeiro.setText("Financeiro   ");
        financeiro.setActionCommand("Financeiro   ");
        financeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-dinheiro-na-mão-20.png"))); // NOI18N
        jMenu1.setText("Constas a Pagar");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        jMenuItem4.setText("Cadastrar");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        jMenuItem5.setText("Consultar");
        jMenu1.add(jMenuItem5);

        financeiro.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-solicitar-dinheiro-20.png"))); // NOI18N
        jMenu2.setText("Contas a Receber");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-20.png"))); // NOI18N
        jMenuItem6.setText("Cadastrar");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-20.png"))); // NOI18N
        jMenuItem7.setText("Consultar");
        jMenu2.add(jMenuItem7);

        financeiro.add(jMenu2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-vendas-totais-20.png"))); // NOI18N
        jMenuItem3.setText("Balanço");
        financeiro.add(jMenuItem3);

        jMenuBar1.add(financeiro);

        relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-apresentação-30.png"))); // NOI18N
        relatorio.setText("Relatrio   ");
        relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(relatorio);

        seguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-trancar-30.png"))); // NOI18N
        seguranca.setText("Segurança   ");
        seguranca.setActionCommand("Segurança   ");
        seguranca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(seguranca);

        ferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-ferramentas-administrativas-30.png"))); // NOI18N
        ferramentas.setText("Ferramentas   ");
        ferramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-imagem-20.png"))); // NOI18N
        jMenu3.setText("Tela de Fundo");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-imagem-20.png"))); // NOI18N
        jMenuItem8.setText("Adicionar Imagem");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-remover-imagem-20.png"))); // NOI18N
        jMenuItem9.setText("Remover Imagem");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-inserir-imagem-raster-20.png"))); // NOI18N
        jMenuItem10.setText("Restaurar Padrão");
        jMenu3.add(jMenuItem10);

        ferramentas.add(jMenu3);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sobre-20.png"))); // NOI18N
        jMenuItem11.setText("Sobre o Sistema");
        ferramentas.add(jMenuItem11);

        jMenuBar1.add(ferramentas);

        sair7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-logout-30.png"))); // NOI18N
        sair7.setText("Sair");
        sair7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(sair7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadFornecedoresActionPerformed

    private void menuCadReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu ferramentas;
    private javax.swing.JMenu financeiro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadReservas;
    private javax.swing.JMenuItem menuCadServicos;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospedes;
    private javax.swing.JMenuItem menuConProdutos;
    private javax.swing.JMenuItem menuConQuartos;
    private javax.swing.JMenuItem menuConReservas;
    private javax.swing.JMenuItem menuConServicos;
    private javax.swing.JMenuItem menuFinalizarReserva;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenu menuHospedes;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuQuartos;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu meunoFuncionarios;
    private javax.swing.JMenu relatorio;
    private javax.swing.JMenu reservas;
    private javax.swing.JMenu sair7;
    private javax.swing.JMenu seguranca;
    private javax.swing.JMenu vendas;
    // End of variables declaration//GEN-END:variables
}
